import {
  HomeOutlined,
  DashboardOutlined,
  AppstoreOutlined,
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  ProfileOutlined,
  LockOutlined,
  FileTextOutlined,
  BookOutlined,
  DatabaseOutlined,
  FundViewOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  PieChartOutlined,
  TableOutlined,
  ShoppingCartOutlined,
  ShopOutlined,
  DollarOutlined,
  PayCircleOutlined,
  ContainerOutlined,
  ToolOutlined,
  NotificationOutlined,
  MessageOutlined,
  MailOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  FolderOutlined,
  FileOutlined,
  FilePdfOutlined,
  FileImageOutlined,
  PictureOutlined,
  VideoCameraOutlined,
  QuestionCircleOutlined,
  InfoCircleOutlined,
  StarOutlined,
  HeartOutlined,
  CloudUploadOutlined,
  CloudDownloadOutlined,
} from '@ant-design/icons';

const icons = {
  HomeOutlined: HomeOutlined,
  DashboardOutlined: DashboardOutlined,
  AppstoreOutlined: AppstoreOutlined,
  SettingOutlined: SettingOutlined,
  UserOutlined: UserOutlined,
  TeamOutlined: TeamOutlined,
  ProfileOutlined: ProfileOutlined,
  LockOutlined: LockOutlined,
  FileTextOutlined: FileTextOutlined,
  BookOutlined: BookOutlined,
  DatabaseOutlined: DatabaseOutlined,
  FundViewOutlined: FundViewOutlined,
  BarChartOutlined: BarChartOutlined,
  AreaChartOutlined: AreaChartOutlined,
  PieChartOutlined: PieChartOutlined,
  TableOutlined: TableOutlined,
  ShoppingCartOutlined: ShoppingCartOutlined,
  ShopOutlined: ShopOutlined,
  DollarOutlined: DollarOutlined,
  PayCircleOutlined: PayCircleOutlined,
  ContainerOutlined: ContainerOutlined,
  ToolOutlined: ToolOutlined,
  NotificationOutlined: NotificationOutlined,
  MessageOutlined: MessageOutlined,
  MailOutlined: MailOutlined,
  CalendarOutlined: CalendarOutlined,
  ClockCircleOutlined: ClockCircleOutlined,
  FolderOutlined: FolderOutlined,
  FileOutlined: FileOutlined,
  FilePdfOutlined: FilePdfOutlined,
  FileImageOutlined: FileImageOutlined,
  PictureOutlined: PictureOutlined,
  VideoCameraOutlined: VideoCameraOutlined,
  QuestionCircleOutlined: QuestionCircleOutlined,
  InfoCircleOutlined: InfoCircleOutlined,
  StarOutlined: StarOutlined,
  HeartOutlined: HeartOutlined,
  CloudUploadOutlined: CloudUploadOutlined,
  CloudDownloadOutlined: CloudDownloadOutlined,
};

export default icons;

