// prisma/seed.js

const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 开始数据初始化...');

  // 1. 插入字典类型
  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_user_sex' },
    update: {},
    create: {
      dictName: '用户性别',
      dictType: 'sys_user_sex',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '用户性别',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_show_hide' },
    update: {},
    create: {
      dictName: '菜单状态',
      dictType: 'sys_show_hide',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '菜单状态',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_normal_disable' },
    update: {},
    create: {
      dictName: '系统开关',
      dictType: 'sys_normal_disable',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '系统开关',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_job_status' },
    update: {},
    create: {
      dictName: '任务状态',
      dictType: 'sys_job_status',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '任务状态',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_job_group' },
    update: {},
    create: {
      dictName: '任务分组',
      dictType: 'sys_job_group',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '任务分组',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_yes_no' },
    update: {},
    create: {
      dictName: '系统是否',
      dictType: 'sys_yes_no',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '系统是否',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_notice_type' },
    update: {},
    create: {
      dictName: '通知类型',
      dictType: 'sys_notice_type',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '通知类型',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_notice_status' },
    update: {},
    create: {
      dictName: '通知状态',
      dictType: 'sys_notice_status',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '通知状态',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_oper_type' },
    update: {},
    create: {
      dictName: '操作类型',
      dictType: 'sys_oper_type',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '操作类型',
    },
  });

  await prisma.sysDictType.upsert({
    where: { dictType: 'sys_common_status' },
    update: {},
    create: {
      dictName: '系统状态',
      dictType: 'sys_common_status',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '系统状态',
    },
  });

  console.log('✅ SysDictType 已创建');

  // 1.1 插入字典数据
  await prisma.sysDictData.createMany({
    data: [
      {
        dictLabel: '男',
        dictValue: '0',
        dictType: 'sys_user_sex',
        dictSort: 1,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '女',
        dictValue: '1',
        dictType: 'sys_user_sex',
        dictSort: 2,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '未知',
        dictValue: '2',
        dictType: 'sys_user_sex',
        dictSort: 3,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '显示',
        dictValue: '0',
        dictType: 'sys_show_hide',
        dictSort: 4,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '隐藏',
        dictValue: '1',
        dictType: 'sys_show_hide',
        dictSort: 5,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_normal_disable',
        dictSort: 6,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '停用',
        dictValue: '1',
        dictType: 'sys_normal_disable',
        dictSort: 7,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_job_status',
        dictSort: 8,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '暂停',
        dictValue: '1',
        dictType: 'sys_job_status',
        dictSort: 9,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '默认',
        dictValue: 'DEFAULT',
        dictType: 'sys_job_group',
        dictSort: 10,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '系统',
        dictValue: 'SYSTEM',
        dictType: 'sys_job_group',
        dictSort: 11,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '是',
        dictValue: 'Y',
        dictType: 'sys_yes_no',
        dictSort: 12,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '否',
        dictValue: 'N',
        dictType: 'sys_yes_no',
        dictSort: 13,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '通知',
        dictValue: '1',
        dictType: 'sys_notice_type',
        dictSort: 14,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '公告',
        dictValue: '2',
        dictType: 'sys_notice_type',
        dictSort: 15,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '正常',
        dictValue: '0',
        dictType: 'sys_notice_status',
        dictSort: 16,
        status: '0',
        isDefault: 'Y',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '关闭',
        dictValue: '1',
        dictType: 'sys_notice_status',
        dictSort: 17,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '其他',
        dictValue: '0',
        dictType: 'sys_oper_type',
        dictSort: 18,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '新增',
        dictValue: '1',
        dictType: 'sys_oper_type',
        dictSort: 19,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '修改',
        dictValue: '2',
        dictType: 'sys_oper_type',
        dictSort: 20,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '删除',
        dictValue: '3',
        dictType: 'sys_oper_type',
        dictSort: 21,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '授权',
        dictValue: '4',
        dictType: 'sys_oper_type',
        dictSort: 22,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '导出',
        dictValue: '5',
        dictType: 'sys_oper_type',
        dictSort: 23,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '导入',
        dictValue: '6',
        dictType: 'sys_oper_type',
        dictSort: 24,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '强退',
        dictValue: '7',
        dictType: 'sys_oper_type',
        dictSort: 25,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '生成代码',
        dictValue: '8',
        dictType: 'sys_oper_type',
        dictSort: 26,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '清空数据',
        dictValue: '9',
        dictType: 'sys_oper_type',
        dictSort: 27,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '成功',
        dictValue: '0',
        dictType: 'sys_common_status',
        dictSort: 28,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        dictLabel: '失败',
        dictValue: '1',
        dictType: 'sys_common_status',
        dictSort: 29,
        status: '0',
        isDefault: 'N',
        createBy: 'admin',
        createTime: new Date(),
      },
    ],
    skipDuplicates: true,
  });

  console.log('✅ SysDictData 已创建');

  // 2. 插入部门（顶级部门）
  const dept = await prisma.sysDept.upsert({
    where: { deptId: 1 },
    update: {},
    create: {
      deptId: 1,
      deptName: 'demo科技有限公司',
      ancestors: ',',
      orderNum: 0,
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const dept1 = await prisma.sysDept.upsert({
    where: { deptId: 2 },
    update: {},
    create: {
      deptId: 2,
      deptName: '南昌总部',
      parentId: dept.deptId,
      ancestors: `,${dept.deptId},2,`,
      orderNum: 1,
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const dept2 = await prisma.sysDept.upsert({
    where: { deptId: 3 },
    update: {},
    create: {
      deptId: 3,
      deptName: '南昌外部',
      parentId: dept.deptId,
      ancestors: `,${dept.deptId},3,`,
      orderNum: 2,
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  await prisma.sysDept.createMany({
    data: [
      {
        deptId: 4,
        deptName: '研发部门',
        parentId: dept1.deptId,
        ancestors: `,${dept.deptId},${dept1.deptId},4,`,
        orderNum: 1,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        deptId: 5,
        deptName: '销售部门',
        parentId: dept1.deptId,
        ancestors: `,${dept.deptId},${dept1.deptId},5,`,
        orderNum: 2,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        deptId: 6,
        deptName: '运营部门',
        parentId: dept1.deptId,
        ancestors: `,${dept.deptId},${dept1.deptId},6,`,
        orderNum: 3,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        deptId: 7,
        deptName: '公关部门',
        parentId: dept1.deptId,
        ancestors: `,${dept.deptId},${dept1.deptId},7,`,
        orderNum: 4,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        deptId: 8,
        deptName: '客服部门',
        parentId: dept2.deptId,
        ancestors: `,${dept.deptId},${dept2.deptId},8,`,
        orderNum: 1,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
      },
      {
        deptId: 9,
        deptName: '售后部门',
        parentId: dept2.deptId,
        ancestors: `,${dept.deptId},${dept2.deptId},9,`,
        orderNum: 2,
        status: '0',
        phone: '17600008888',
        leader: '张三',
        email: 'mock.user.2025@example.com',
        createBy: 'admin',
        createTime: new Date(),
      },
    ],
  });

  console.log('✅ SysDept 已创建');

  // 3. 插入岗位
  const post = await prisma.sysPost.upsert({
    where: { postCode: 'ceo' },
    update: {},
    create: {
      postCode: `ceo`,
      postName: '董事长',
      postSort: 1,
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '董事长',
    },
  });

  await prisma.sysPost.createMany({
    data: [
      {
        postCode: `se`,
        postName: '项目经理',
        postSort: 2,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
        remark: '项目经理',
      },
      {
        postCode: `hr`,
        postName: '人力资源',
        postSort: 3,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
        remark: '人力资源',
      },
      {
        postCode: `user`,
        postName: '普通员工',
        postSort: 4,
        status: '0',
        createBy: 'admin',
        createTime: new Date(),
        remark: '普通员工',
      },
    ],
    skipDuplicates: true,
  });

  console.log('✅ SysPost 已创建');

  // 4. 插入角色
  const role = await prisma.sysRole.upsert({
    where: { roleId: 1 },
    update: {},
    create: {
      roleId: 1,
      roleName: '超级管理员',
      roleKey: 'admin',
      roleSort: 1,
      status: '0',
      dataScope: '1', // 所有数据
      createBy: 'admin',
      createTime: new Date(),
      remark: '内置管理员角色',
    },
  });

  const role1 = await prisma.sysRole.upsert({
    where: { roleId: 2 },
    update: {},
    create: {
      roleId: 2,
      roleName: '普通角色',
      roleKey: 'common',
      roleSort: 2,
      status: '0',
      dataScope: '2', // 自定权限数据
      createBy: 'admin',
      createTime: new Date(),
      remark: '普通角色',
    },
  });

  console.log('✅ SysRole 已创建');

  // 5. 插入菜单（根菜单）
  const welcomeMenu = await prisma.sysMenu.upsert({
    where: { menuId: 1 },
    update: {},
    create: {
      menuId: 1,
      menuName: '🎉 欢迎页',
      parentId: null,
      orderNum: 1,
      path: 'welcome',
      component: '/Welcome',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'welcome:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const sysMenu = await prisma.sysMenu.upsert({
    where: { menuId: 2 },
    update: {},
    create: {
      menuId: 2,
      menuName: '系统管理',
      parentId: null,
      orderNum: 2,
      path: 'system',
      component: 'Layout',
      menuType: 'M',
      visible: '0',
      status: '0',
      icon: 'AppstoreOutlined',
      perms: null,
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const moirMenu = await prisma.sysMenu.upsert({
    where: { menuId: 3 },
    update: {},
    create: {
      menuId: 3,
      menuName: '系统监控',
      parentId: null,
      orderNum: 3,
      path: 'monitor',
      component: 'Layout',
      menuType: 'M',
      visible: '0',
      status: '0',
      icon: 'FundViewOutlined',
      perms: null,
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const toolMenu = await prisma.sysMenu.upsert({
    where: { menuId: 4 },
    update: {},
    create: {
      menuId: 4,
      menuName: '系统工具',
      parentId: null,
      orderNum: 4,
      path: 'tool',
      component: 'Layout',
      menuType: 'M',
      visible: '0',
      status: '0',
      icon: 'ToolOutlined',
      perms: null,
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const userMenu = await prisma.sysMenu.upsert({
    where: { menuId: 5 },
    update: {},
    create: {
      menuId: 5,
      menuName: '用户管理',
      parentId: sysMenu.menuId,
      orderNum: 1,
      path: 'user',
      component: '/System/User/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:user:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const roleMenu = await prisma.sysMenu.upsert({
    where: { menuId: 6 },
    update: {},
    create: {
      menuId: 6,
      menuName: '角色管理',
      parentId: sysMenu.menuId,
      orderNum: 2,
      path: 'role',
      component: '/System/Role/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:role:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const navMenu = await prisma.sysMenu.upsert({
    where: { menuId: 7 },
    update: {},
    create: {
      menuId: 7,
      menuName: '菜单管理',
      parentId: sysMenu.menuId,
      orderNum: 3,
      path: 'menu',
      component: '/System/Menu/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:menu:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const deptMenu = await prisma.sysMenu.upsert({
    where: { menuId: 8 },
    update: {},
    create: {
      menuId: 8,
      menuName: '部门管理',
      parentId: sysMenu.menuId,
      orderNum: 4,
      path: 'dept',
      component: '/System/Dept/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:dept:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const postMenu = await prisma.sysMenu.upsert({
    where: { menuId: 9 },
    update: {},
    create: {
      menuId: 9,
      menuName: '岗位管理',
      parentId: sysMenu.menuId,
      orderNum: 5,
      path: 'post',
      component: '/System/Post/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:post:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const dictMenu = await prisma.sysMenu.upsert({
    where: { menuId: 10 },
    update: {},
    create: {
      menuId: 10,
      menuName: '字典管理',
      parentId: sysMenu.menuId,
      orderNum: 6,
      path: 'dict',
      component: '/System/Dict/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:dict:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const dictDataMenu = await prisma.sysMenu.upsert({
    where: { menuId: 11 },
    update: {},
    create: {
      menuId: 11,
      menuName: '字典数据',
      parentId: sysMenu.menuId,
      orderNum: 7,
      path: 'dict/:dictId',
      component: '/System/DictData/index',
      menuType: 'C',
      visible: '1',
      status: '0',
      icon: '',
      perms: 'system:dictData:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const configMenu = await prisma.sysMenu.upsert({
    where: { menuId: 12 },
    update: {},
    create: {
      menuId: 12,
      menuName: '参数设置',
      parentId: sysMenu.menuId,
      orderNum: 8,
      path: 'config',
      component: '/System/Config/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:config:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const noticeMenu = await prisma.sysMenu.upsert({
    where: { menuId: 13 },
    update: {},
    create: {
      menuId: 13,
      menuName: '通知公告',
      parentId: sysMenu.menuId,
      orderNum: 9,
      path: 'notice',
      component: '/System/Notice/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'system:notice:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const logMenu = await prisma.sysMenu.upsert({
    where: { menuId: 14 },
    update: {},
    create: {
      menuId: 14,
      menuName: '日志管理',
      parentId: sysMenu.menuId,
      orderNum: 10,
      path: 'log',
      component: null,
      menuType: 'M',
      visible: '0',
      status: '0',
      icon: '',
      perms: null,
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const operlogMenu = await prisma.sysMenu.upsert({
    where: { menuId: 15 },
    update: {},
    create: {
      menuId: 15,
      menuName: '操作日志',
      parentId: logMenu.menuId,
      orderNum: 1,
      path: 'operlog',
      component: '/Monitor/Operlog/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'monitor:operlog:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const logininforMenu = await prisma.sysMenu.upsert({
    where: { menuId: 16 },
    update: {},
    create: {
      menuId: 16,
      menuName: '登录日志',
      parentId: logMenu.menuId,
      orderNum: 2,
      path: 'logininfor',
      component: '/Monitor/Logininfor/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'monitor:logininfor:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const onlineMenu = await prisma.sysMenu.upsert({
    where: { menuId: 17 },
    update: {},
    create: {
      menuId: 17,
      menuName: '在线用户',
      parentId: moirMenu.menuId,
      orderNum: 1,
      path: 'online',
      component: '/Monitor/Online/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'monitor:online:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const jobMenu = await prisma.sysMenu.upsert({
    where: { menuId: 18 },
    update: {},
    create: {
      menuId: 18,
      menuName: '定时任务',
      parentId: moirMenu.menuId,
      orderNum: 2,
      path: 'job',
      component: '/Monitor/Job/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'monitor:job:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const jobLogMenu = await prisma.sysMenu.upsert({
    where: { menuId: 19 },
    update: {},
    create: {
      menuId: 19,
      menuName: '调度日志',
      parentId: moirMenu.menuId,
      orderNum: 3,
      path: 'job/log',
      component: '/Monitor/JobLog/index',
      menuType: 'C',
      visible: '1',
      status: '0',
      icon: '',
      perms: 'monitor:user:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const cacheMenu = await prisma.sysMenu.upsert({
    where: { menuId: 20 },
    update: {},
    create: {
      menuId: 20,
      menuName: '缓存监控',
      parentId: moirMenu.menuId,
      orderNum: 4,
      path: 'cache',
      component: '/Monitor/Cache/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'monitor:cache:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const cacheListMenu = await prisma.sysMenu.upsert({
    where: { menuId: 21 },
    update: {},
    create: {
      menuId: 21,
      menuName: '缓存列表',
      parentId: moirMenu.menuId,
      orderNum: 5,
      path: 'cacheList',
      component: '/Monitor/CacheList/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'monitor:cacheList:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const genMenu = await prisma.sysMenu.upsert({
    where: { menuId: 22 },
    update: {},
    create: {
      menuId: 22,
      menuName: '代码生成',
      parentId: toolMenu.menuId,
      orderNum: 1,
      path: 'gen',
      component: '/Tool/gen/index',
      menuType: 'C',
      visible: '0',
      status: '0',
      icon: '',
      perms: 'tool:gen:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  const setMenu = await prisma.sysMenu.upsert({
    where: { menuId: 1000 },
    update: {},
    create: {
      menuId: 1000,
      menuName: '个人设置',
      parentId: null,
      orderNum: 1,
      path: 'settings',
      component: '/Settings/index',
      menuType: 'C',
      visible: '1',
      status: '0',
      icon: '',
      perms: 'settings:list',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  await prisma.sysMenu.createMany({
    data: [
      {
        menuName: '用户查询',
        parentId: userMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:user:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '用户查询',
      },
      {
        menuName: '用户新增',
        parentId: userMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:user:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '用户新增',
      },
      {
        menuName: '用户修改',
        parentId: userMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:user:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '用户修改',
      },
      {
        menuName: '用户删除',
        parentId: userMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:user:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '用户删除',
      },
      {
        menuName: '用户导出',
        parentId: userMenu.menuId,
        orderNum: 5,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:user:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '用户导出',
      },
      {
        menuName: '用户导入',
        parentId: userMenu.menuId,
        orderNum: 6,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:user:import',
        createBy: 'admin',
        createTime: new Date(),
        remark: '用户导入',
      },
      {
        menuName: '重置密码',
        parentId: userMenu.menuId,
        orderNum: 7,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:user:resetPwd',
        createBy: 'admin',
        createTime: new Date(),
        remark: '重置密码',
      },
      {
        menuName: '角色查询',
        parentId: roleMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:role:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '角色查询',
      },
      {
        menuName: '角色新增',
        parentId: roleMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:role:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '角色新增',
      },
      {
        menuName: '角色修改',
        parentId: roleMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:role:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '角色修改',
      },
      {
        menuName: '角色删除',
        parentId: roleMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:role:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '角色删除',
      },
      {
        menuName: '角色导出',
        parentId: roleMenu.menuId,
        orderNum: 5,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:role:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '角色导出',
      },
      {
        menuName: '菜单查询',
        parentId: navMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:menu:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '菜单查询',
      },
      {
        menuName: '菜单新增',
        parentId: navMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:menu:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '菜单新增',
      },
      {
        menuName: '菜单修改',
        parentId: navMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:menu:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '菜单修改',
      },
      {
        menuName: '菜单删除',
        parentId: navMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:menu:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '菜单删除',
      },
      {
        menuName: '部门查询',
        parentId: deptMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dept:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '部门查询',
      },
      {
        menuName: '部门新增',
        parentId: deptMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dept:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '部门新增',
      },
      {
        menuName: '部门修改',
        parentId: deptMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dept:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '部门修改',
      },
      {
        menuName: '部门删除',
        parentId: deptMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dept:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '部门删除',
      },
      {
        menuName: '岗位查询',
        parentId: postMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:post:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '岗位查询',
      },
      {
        menuName: '岗位新增',
        parentId: postMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:post:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '岗位新增',
      },
      {
        menuName: '岗位修改',
        parentId: postMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:post:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '岗位修改',
      },
      {
        menuName: '岗位删除',
        parentId: postMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:post:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '岗位删除',
      },
      {
        menuName: '岗位导出',
        parentId: postMenu.menuId,
        orderNum: 5,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:post:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '岗位导出',
      },
      {
        menuName: '字典查询',
        parentId: dictMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dict:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '字典查询',
      },
      {
        menuName: '字典新增',
        parentId: dictMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dict:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '字典新增',
      },
      {
        menuName: '字典修改',
        parentId: dictMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dict:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '字典修改',
      },
      {
        menuName: '字典删除',
        parentId: dictMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dict:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '字典删除',
      },
      {
        menuName: '字典导出',
        parentId: dictMenu.menuId,
        orderNum: 5,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:dict:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '字典导出',
      },
      {
        menuName: '参数查询',
        parentId: configMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:config:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '参数查询',
      },
      {
        menuName: '参数新增',
        parentId: configMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:config:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '参数新增',
      },
      {
        menuName: '参数修改',
        parentId: configMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:config:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '参数修改',
      },
      {
        menuName: '参数删除',
        parentId: configMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:config:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '参数删除',
      },
      {
        menuName: '参数导出',
        parentId: configMenu.menuId,
        orderNum: 5,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:config:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '参数导出',
      },
      {
        menuName: '公告查询',
        parentId: noticeMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:notice:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '公告查询',
      },
      {
        menuName: '公告新增',
        parentId: noticeMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:notice:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '公告新增',
      },
      {
        menuName: '公告修改',
        parentId: noticeMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:notice:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '公告修改',
      },
      {
        menuName: '公告删除',
        parentId: noticeMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'system:notice:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '公告删除',
      },
      {
        menuName: '操作查询',
        parentId: operlogMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:operlog:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '操作查询',
      },
      {
        menuName: '操作删除',
        parentId: operlogMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:operlog:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '操作删除',
      },
      {
        menuName: '日志导出',
        parentId: operlogMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:operlog:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '日志导出',
      },
      {
        menuName: '登录查询',
        parentId: logininforMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:logininfor:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '登录查询',
      },
      {
        menuName: '登录删除',
        parentId: logininforMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:logininfor:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '登录删除',
      },
      {
        menuName: '日志导出',
        parentId: logininforMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:logininfor:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '日志导出',
      },
      {
        menuName: '账户解锁',
        parentId: logininforMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:logininfor:unlock',
        createBy: 'admin',
        createTime: new Date(),
        remark: '账户解锁',
      },
      {
        menuName: '在线查询',
        parentId: onlineMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:online:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '在线查询',
      },
      {
        menuName: '批量强退',
        parentId: onlineMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:online:batchLogout',
        createBy: 'admin',
        createTime: new Date(),
        remark: '批量强退',
      },
      {
        menuName: '单条强退',
        parentId: onlineMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:online:forceLogout',
        createBy: 'admin',
        createTime: new Date(),
        remark: '单条强退',
      },
      {
        menuName: '任务查询',
        parentId: jobMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:job:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '任务查询',
      },
      {
        menuName: '任务新增',
        parentId: jobMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:job:add',
        createBy: 'admin',
        createTime: new Date(),
        remark: '任务新增',
      },
      {
        menuName: '任务修改',
        parentId: jobMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:job:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '任务修改',
      },
      {
        menuName: '任务删除',
        parentId: jobMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:job:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '任务删除',
      },
      {
        menuName: '状态修改',
        parentId: jobMenu.menuId,
        orderNum: 5,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:job:changeStatus',
        createBy: 'admin',
        createTime: new Date(),
        remark: '状态修改',
      },
      {
        menuName: '任务导出',
        parentId: jobMenu.menuId,
        orderNum: 6,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'monitor:job:export',
        createBy: 'admin',
        createTime: new Date(),
        remark: '任务导出',
      },
      {
        menuName: '生成查询',
        parentId: genMenu.menuId,
        orderNum: 1,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'tool:gen:query',
        createBy: 'admin',
        createTime: new Date(),
        remark: '生成查询',
      },
      {
        menuName: '生成修改',
        parentId: genMenu.menuId,
        orderNum: 2,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'tool:gen:edit',
        createBy: 'admin',
        createTime: new Date(),
        remark: '生成修改',
      },
      {
        menuName: '生成删除',
        parentId: genMenu.menuId,
        orderNum: 3,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'tool:gen:remove',
        createBy: 'admin',
        createTime: new Date(),
        remark: '生成删除',
      },
      {
        menuName: '导入代码',
        parentId: genMenu.menuId,
        orderNum: 4,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'tool:gen:import',
        createBy: 'admin',
        createTime: new Date(),
        remark: '导入代码',
      },
      {
        menuName: '预览代码',
        parentId: genMenu.menuId,
        orderNum: 5,
        path: null,
        component: null,
        menuType: 'F',
        visible: '0',
        status: '0',
        icon: '',
        perms: 'tool:gen:preview',
        createBy: 'admin',
        createTime: new Date(),
        remark: '预览代码',
      },
    ],
  });

  console.log('✅ SysMenu 已创建');

  // 6、创建定时任务
  const job = await prisma.sysJob.upsert({
    where: { jobId: 1 },
    update: {},
    create: {
      jobId: 1,
      jobName: '测试任务',
      jobGroup: 'DEFAULT',
      invokeTarget: 'JobService.demo(1,2,3,true)',
      cronExpression: '* * * * *',
      misfirePolicy: '1',
      concurrent: '1',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      remark: '测试任务'
    }
  })

  console.log('✅ SysJob 已创建');

  // 7. 创建用户（关联部门、岗位、角色）
  const user = await prisma.sysUser.create({
    data: {
      userName: 'admin',
      nickName: '超级管理员',
      password: '$2b$10$dfDByASRziLltpJ9OQ8cTuSeaz3Kqv.BR1MWQoQ1bR3UfgEKYE0w6', // 明文密码应由你加密
      phonenumber: '17600008888',
      email: 'mock.user.2025@example.com',
      sex: '0',
      status: '0',
      createBy: 'admin',
      createTime: new Date(),
      dept: {
        connect: { deptId: dept.deptId },
      },
      posts: {
        connect: { postId: post.postId },
      },
      roles: {
        connect: { roleId: role.roleId },
      },
    },
  });
  console.log('✅ SysUser 已创建');

  // 8. 插入用户个性化设置（SysWeb）
  await prisma.sysWeb.create({
    data: {
      userId: user.userId,
      theme: '{"layout":"light","colorPrimary":"#1677FF","colorInfo": "#1677FF"}',
      createBy: 'admin',
      createTime: new Date(),
    },
  });

  console.log('✅ SysWeb 已创建');

  // 9. 插入系统配置
  await prisma.sysConfig.create({
    data: {
      configName: '主框架页-默认皮肤样式名称',
      configKey: 'sys.index.skinName',
      configValue: '蓝色皮肤',
      configType: 'Y',
      createBy: 'admin',
      createTime: new Date(),
      remark: '默认 skin-blue',
    },
  });
  console.log('✅ SysConfig 已创建');

  // 10. （可选）给角色分配菜单权限
  await prisma.sysRole.update({
    where: { roleId: role.roleId },
    data: {
      menus: {
        connect: { menuId: sysMenu.menuId },
      },
    },
  });
  console.log('✅ 角色已分配菜单权限');

  // 11. （可选）给角色分配部门数据权限
  await prisma.sysRole.update({
    where: { roleId: role.roleId },
    data: {
      depts: {
        connect: { deptId: dept.deptId },
      },
    },
  });
  console.log('✅ 角色已分配部门数据权限');

  console.log('🎉 数据初始化完成！');
}

main()
  .catch((e) => {
    console.error('❌ 数据初始化失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
